---
- name: Ansible PostgresSQL tests
  hosts: 127.0.0.1
  gather_facts: no
  tasks:
    - name: PostgreSQL Server ping test
      postgresql_ping:
        db: postgres
        # login_host is postgresdb ip address
        # login_host may be different on your machine
        login_host: 172.18.0.2
        login_user: postgres
        login_password: 123
...
